### PR TITLE
robust json parsing & entity extraction progress log

### PR DESCRIPTION
**Pull request by rangehow**
1. The JSON generated by large models may have issues such as being incomplete, redundant, or having formatting errors. The original solution was too brief and provided few prompts, so we made some improvements to address these.
2. Entity extraction is the most time-consuming part of this project, but there was no explicit progress indicator. We added a percentage indicator to let users know the current progress more clearly.

### CODE REVIEW

**Comment by NazimHAli** [comment]
I didn't see this PR until now, yesterday I ended up adding `tqdm` to every task so that all the progress was available by default. Happy to help with this if needed :+1:

**Comment by rangehow** [comment]
> I didn't see this PR until now, yesterday I ended up adding `tqdm` to every task so that all the progress bars were available by default. Happy to help with this if needed.

Hi @NazimHAli. You can bring up a new PR, and I will reorganize the submitted code by removing the percentage related parts. But it's better to do it quickly, because tonight this PR will be merged.

**Comment by rangehow** [comment]
@gusye1234 cc

**Comment by NazimHAli** [comment]
> > I didn't see this PR until now, yesterday I ended up adding `tqdm` to every task so that all the progress bars were available by default. Happy to help with this if needed.
> 
> Hi @NazimHAli. You can bring up a new PR, and I will reorganize the submitted code by removing the percentage related parts. But it's better to do it quickly, because tonight this PR will be merged.

I won't have time to do it before this gets merged. You can continue with this change and I can do a follow-up later.

**Pull request merged**
