### PR TITLE
fix:optimize neo4j cypher statement

### PR DESCRIPTION
**Pull request by KKenny0**
## Pre-Checklist

- [x] I have read through the [CONTRIBUTING.md](https://github.com/gusye1234/nano-graphrag/blob/main/docs/CONTRIBUTING.md) documentation.
- [x] I have tested the new statement.

## Description

I was prompted by the `Syntex Error` when I was using the original statement in my environment: neo4j = = 4.4.38, GDS = 2.6.2, so I tried to optimize the original statement to make the program work.

### CODE REVIEW

**Comment by gusye1234** [comment]
I was testing neo4j with kernel version "5.23.0".
Did the syntax you use will cause errros in the latest version?

**Comment by KKenny0** [comment]
> I was testing neo4j with kernel version "5.23.0". Did the syntax you use will cause errros in the latest version?

Ok, I noticed that the syntax I was using was deprecated in the version 5.x. Maybe we can tweak the code so that it works for both 4.x and 5.x versions.

**Comment by gusye1234** [comment]
Maybe you can fork a neo4j version 4 storage in another file?
Seem like 4 and 5 are pretty different

**Comment by KKenny0** [comment]
> Maybe you can fork a neo4j version 4 storage in another file? Seem like 4 and 5 are pretty different

In fact, I mention this PR just to hint at potential problems. Perhaps a note in the README about neo4j version dependencies would be helpful to users.

**Comment by promentol** [comment]
```
[2024-12-04 15:08:09,085: ERROR/ForkPoolWorker-7] Error while inserting data: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input '.6510875044767086': expected a parameter, '&', ')', ':', 'WHERE', '{' or '|' (line 1, column 53 (offset: 52))
"MATCH (n:local_test_0_6510875044767086__local_test_0.6510875044767086:chunk_entity_relation) WHERE n.id = $node_id RETURN properties(n) AS node_data"
            
```

I am getting this error, confirming, I am using `neo4j:5.23.0` in docker 

What may be the problem?

**Comment by KKenny0** [comment]
> ```
> [2024-12-04 15:08:09,085: ERROR/ForkPoolWorker-7] Error while inserting data: {code: Neo.ClientError.Statement.SyntaxError} {message: Invalid input '.6510875044767086': expected a parameter, '&', ')', ':', 'WHERE', '{' or '|' (line 1, column 53 (offset: 52))
> "MATCH (n:local_test_0_6510875044767086__local_test_0.6510875044767086:chunk_entity_relation) WHERE n.id = $node_id RETURN properties(n) AS node_data"
>             
> ```
> 
> I am getting this error, confirming, I am using `neo4j:5.23.0` in docker
> 
> What may be the problem?

The issue is likely due to the use of a period (.) in the label name `0.6510875044767086`

**Pull request closed without merging**
